[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/coingecko/*"
  to = "https://api.coingecko.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/fmp/*"
  to = "https://financialmodelingprep.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-production-api.com"
  VITE_WS_URL = "wss://your-production-ws.com/ws"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-staging-api.com"
  VITE_WS_URL = "wss://your-staging-ws.com/ws"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ACCEPT"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https: wss:; font-src 'self' data:;"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"